---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - Java
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.java"
  - "**.c"
  - "**.js"
  - "**.jsx"
exclude_paths:
  - "**.js"
  - "**.we"
